"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { CopilotSidebar } from "@copilotkit/react-ui";
import { useCopilotAction, useRenderToolCall } from "@copilotkit/react-core";
import "@copilotkit/react-ui/styles.css";
import { useThreadContext } from "./providers";
import { C1Component, ThemeProvider } from "@thesysai/genui-sdk";
import { themePresets } from "@crayonai/react-ui";
import "@crayonai/react-ui/styles/index.css";
import MedicalTreatmentOverview from "../components/MedicalTreatmentOverview";
import CaseSnapshot from "../components/CaseSnapshot";
import CaseDashboard from "../components/CaseDashboard";
import InsuranceCoverageCard from "../components/InsuranceCoverageCard";
import LienCard from "../components/LienCard";
import ExpenseCard from "../components/ExpenseCard";
import ContactCard from "../components/ContactCard";
import ComposedView from "../components/ComposedView";
import NegotiationsView from "../components/NegotiationsView";
import NotesView from "../components/NotesView";
import CalendarView from "../components/CalendarView";
import DocumentViewer from "../components/DocumentViewer";

// Type for thread data from LangGraph API
interface Thread {
  thread_id: string;
  created_at: string;
  updated_at: string;
  metadata: Record<string, unknown>;
  status?: "idle" | "busy" | "interrupted" | "error";
  // Computed from recent runs
  lastMessage?: string;
  runStatus?: "running" | "complete" | "error";
}

// Type for the UI artifact generated by the agent
interface GeneratedArtifact {
  ui_content: string;
  ui_type: string;
  instruction?: string;
  data?: Record<string, unknown>;
  artifact_id?: string;
  artifact_type?: string;
  // For custom template rendering (e.g., MedicalTreatmentOverview)
  component?: string;
  componentData?: Record<string, unknown>;
}

// Thread list sidebar component
function ThreadList({
  threads,
  currentThreadId,
  onSelectThread,
  onNewThread,
  isLoading,
}: {
  threads: Thread[];
  currentThreadId: string | null;
  onSelectThread: (threadId: string) => void;
  onNewThread: () => void;
  isLoading: boolean;
}) {
  // Get status indicator
  const getStatusIndicator = (thread: Thread) => {
    if (thread.runStatus === "running" || thread.status === "busy") {
      return <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" title="Running" />;
    }
    if (thread.runStatus === "error" || thread.status === "error") {
      return <span className="w-2 h-2 rounded-full bg-red-500" title="Error" />;
    }
    return <span className="w-2 h-2 rounded-full bg-emerald-500" title="Complete" />;
  };

  // Format timestamp
  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    
    if (diff < 60000) return "Just now";
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`;
    return date.toLocaleDateString();
  };

  return (
    <div className="w-64 bg-zinc-900 border-r border-zinc-800 flex flex-col h-full">
      {/* Header */}
      <div className="p-4 border-b border-zinc-800">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-zinc-300">Threads</h2>
          <button
            onClick={onNewThread}
            className="p-1.5 rounded-lg bg-emerald-500/20 text-emerald-400 hover:bg-emerald-500/30 transition-colors"
            title="New Thread"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
          </button>
        </div>
        
        {/* Legend */}
        <div className="flex items-center gap-3 text-xs text-zinc-500">
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-blue-500" /> Running
          </span>
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-emerald-500" /> Done
          </span>
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-red-500" /> Error
          </span>
        </div>
      </div>

      {/* Thread list */}
      <div className="flex-1 overflow-y-auto">
        {isLoading ? (
          <div className="p-4 text-center text-zinc-500 text-sm">
            Loading threads...
          </div>
        ) : threads.length === 0 ? (
          <div className="p-4 text-center text-zinc-500 text-sm">
            No threads yet. Start a conversation!
          </div>
        ) : (
          threads.map((thread) => (
            <button
              key={thread.thread_id}
              onClick={() => onSelectThread(thread.thread_id)}
              className={`w-full p-3 text-left border-b border-zinc-800/50 hover:bg-zinc-800/50 transition-colors ${
                currentThreadId === thread.thread_id ? "bg-zinc-800 border-l-2 border-l-emerald-500" : ""
              }`}
            >
              <div className="flex items-center gap-2 mb-1">
                {getStatusIndicator(thread)}
                <span className="text-xs text-zinc-500 truncate">
                  {thread.thread_id.slice(0, 8)}...
                </span>
                <span className="text-xs text-zinc-600 ml-auto">
                  {formatTime(thread.updated_at || thread.created_at)}
                </span>
              </div>
              {thread.lastMessage && (
                <p className="text-xs text-zinc-400 truncate">
                  {thread.lastMessage}
                </p>
              )}
            </button>
          ))
        )}
      </div>

      {/* Refresh button */}
      <div className="p-3 border-t border-zinc-800">
        <button
          onClick={() => window.location.reload()}
          className="w-full py-2 px-3 text-xs text-zinc-400 hover:text-zinc-300 hover:bg-zinc-800 rounded-lg transition-colors"
        >
          ↻ Refresh threads
        </button>
      </div>
    </div>
  );
}

// Main content area - displays generated UI artifacts
function MainContent({ artifact }: { artifact: GeneratedArtifact | null }) {
  if (!artifact) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8">
        <div className="max-w-2xl text-center space-y-6">
          <div className="w-24 h-24 mx-auto bg-gradient-to-br from-emerald-500 to-teal-600 rounded-2xl flex items-center justify-center shadow-2xl shadow-emerald-500/20">
            <svg
              className="w-12 h-12 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1.5}
                d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
              />
            </svg>
          </div>
          
          <h1 className="text-4xl font-bold bg-gradient-to-r from-emerald-400 to-teal-400 bg-clip-text text-transparent">
            Roscoe
          </h1>
          
          <p className="text-zinc-400 text-lg">
            Your AI-powered paralegal assistant. Ask me to research cases, 
            draft demand letters, analyze documents, or manage your legal tasks.
          </p>

          <div className="grid grid-cols-2 gap-4 pt-4">
            {[
              { icon: "📋", label: "Case Cards", desc: "View rich case summaries" },
              { icon: "🏥", label: "Medical Overview", desc: "Provider files & billing" },
              { icon: "📈", label: "Timelines", desc: "Visualize medical treatment" },
              { icon: "📊", label: "Dashboards", desc: "Case overview displays" },
            ].map((item) => (
              <div
                key={item.label}
                className="p-4 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-emerald-500/50 transition-colors cursor-pointer group"
              >
                <span className="text-2xl">{item.icon}</span>
                <h3 className="font-semibold text-zinc-200 mt-2 group-hover:text-emerald-400 transition-colors">
                  {item.label}
                </h3>
                <p className="text-sm text-zinc-500">{item.desc}</p>
              </div>
            ))}
          </div>

          <p className="text-zinc-500 text-sm pt-4">
            💡 Try: &quot;Show medical overview for [client name]&quot;
          </p>
        </div>
      </div>
    );
  }

  // Render custom components based on component name
  const componentName = artifact.component;
  const componentData = artifact.componentData || artifact.data;

  if (componentName && componentData) {
    // Get badge color and label based on component type
    const getBadgeStyle = (name: string) => {
      switch (name) {
        case "MedicalTreatmentOverview":
        case "MedicalProviderCard":
          return { bg: "bg-purple-500/20", text: "text-purple-400", label: "MEDICAL" };
        case "CaseSnapshot":
          return { bg: "bg-emerald-500/20", text: "text-emerald-400", label: "CASE SNAPSHOT" };
        case "CaseDashboard":
          return { bg: "bg-blue-500/20", text: "text-blue-400", label: "CASE DASHBOARD" };
        case "InsuranceCoverageCard":
        case "InsuranceOverview":
          return { bg: "bg-indigo-500/20", text: "text-indigo-400", label: "INSURANCE" };
        case "LienCard":
          return { bg: "bg-orange-500/20", text: "text-orange-400", label: "LIENS" };
        case "ExpenseCard":
          return { bg: "bg-pink-500/20", text: "text-pink-400", label: "EXPENSES" };
        case "ContactCard":
          return { bg: "bg-cyan-500/20", text: "text-cyan-400", label: "CONTACT" };
        case "ComposedView":
          return { bg: "bg-amber-500/20", text: "text-amber-400", label: "CUSTOM VIEW" };
        case "NegotiationsView":
          return { bg: "bg-yellow-500/20", text: "text-yellow-400", label: "NEGOTIATIONS" };
        case "NotesView":
          return { bg: "bg-indigo-500/20", text: "text-indigo-400", label: "NOTES" };
        case "CalendarView":
          return { bg: "bg-teal-500/20", text: "text-teal-400", label: "CALENDAR" };
        case "DocumentViewer":
          return { bg: "bg-rose-500/20", text: "text-rose-400", label: "DOCUMENT" };
        default:
          return { bg: "bg-zinc-500/20", text: "text-zinc-400", label: name.toUpperCase() };
      }
    };

    const badge = getBadgeStyle(componentName);

    // Render the appropriate component
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const renderComponent = () => {
      // Cast to any to allow flexible data types from agent
      const data = componentData as any;
      switch (componentName) {
        case "MedicalTreatmentOverview":
          return <MedicalTreatmentOverview data={data} />;
        case "CaseSnapshot":
          return <CaseSnapshot data={data} />;
        case "CaseDashboard":
          return <CaseDashboard data={data} />;
        case "InsuranceCoverageCard":
        case "InsuranceOverview":
          return <InsuranceCoverageCard data={data} />;
        case "MedicalProviderCard":
          // Single provider - wrap in array for the component
          return <MedicalTreatmentOverview data={{
            client_name: "",
            case_name: "",
            total_billed: 0,
            providers: [data]
          }} />;
        case "LienCard":
          return <LienCard data={data} />;
        case "ExpenseCard":
          return <ExpenseCard data={data} />;
        case "ContactCard":
          return <ContactCard data={data} />;
        case "ComposedView":
          return <ComposedView data={data} />;
        case "NegotiationsView":
          return <NegotiationsView data={data} />;
        case "NotesView":
          return <NotesView data={data} />;
        case "CalendarView":
          return <CalendarView data={data} />;
        case "DocumentViewer":
          return <DocumentViewer data={data} />;
        default:
          return (
            <div className="text-zinc-400">
              <p>Unknown component: {componentName}</p>
              <pre className="mt-2 text-xs overflow-auto">{JSON.stringify(componentData, null, 2)}</pre>
            </div>
          );
      }
    };

    return (
      <div className="flex-1 flex flex-col p-6 overflow-auto">
        <div className="max-w-5xl mx-auto w-full">
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className={`text-xs px-2 py-1 rounded ${badge.bg} ${badge.text} font-medium`}>
                {badge.label}
              </span>
            </div>
          </div>

          <div className="bg-zinc-900/50 rounded-xl border border-zinc-800 p-6">
            {renderComponent()}
          </div>
        </div>
      </div>
    );
  }

  // Default: Render C1 component for Thesys UI
  return (
    <div className="flex-1 flex flex-col p-6 overflow-auto">
      <div className="max-w-4xl mx-auto w-full">
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xs px-2 py-1 rounded bg-emerald-500/20 text-emerald-400 font-medium">
              {artifact.ui_type.toUpperCase()}
            </span>
            {artifact.instruction && (
              <span className="text-zinc-500 text-sm truncate max-w-md">
                {artifact.instruction}
              </span>
            )}
          </div>
        </div>

        <div className="bg-zinc-900/50 rounded-xl border border-zinc-800 p-6">
          <ThemeProvider
            theme={themePresets.neon.theme}
            darkTheme={themePresets.neon.darkTheme}
            mode="dark"
          >
            <C1Component
              c1Response={artifact.ui_content}
              isStreaming={false}
              onAction={(action) => {
                console.log("User action on UI component:", action);
              }}
            />
          </ThemeProvider>
        </div>
      </div>
    </div>
  );
}

export default function Page() {
  const [currentArtifact, setCurrentArtifact] = useState<GeneratedArtifact | null>(null);
  
  // Track which tool call results we've already processed to prevent infinite loops
  // Keys are permanent per page session - each tool call only captures once
  const capturedResultsRef = useRef<Set<string>>(new Set());
  
  // Thread management state
  const [threads, setThreads] = useState<Thread[]>([]);
  const [isLoadingThreads, setIsLoadingThreads] = useState(true);
  const [showThreadList, setShowThreadList] = useState(true);

  // Get thread context - this manages threadId at the provider level
  // This ensures CopilotKit re-renders when thread changes
  const { threadId: currentThreadId, setThreadId } = useThreadContext();

  // Fetch threads from LangGraph API
  const fetchThreads = useCallback(async () => {
    try {
      setIsLoadingThreads(true);
      const response = await fetch("/api/threads");
      if (response.ok) {
        const data = await response.json();
        setThreads(data.threads || []);
      }
    } catch (error) {
      console.error("Failed to fetch threads:", error);
    } finally {
      setIsLoadingThreads(false);
    }
  }, []);

  // Fetch threads on mount and periodically
  useEffect(() => {
    fetchThreads();
    const interval = setInterval(fetchThreads, 10000); // Refresh every 10s
    return () => clearInterval(interval);
  }, [fetchThreads]);

  // Handle thread selection - updates threadId at provider level
  // CopilotKit will internally load the new thread's messages without remounting
  const handleSelectThread = useCallback((selectedThreadId: string) => {
    console.log("[Thread] Switching to thread:", selectedThreadId);
    setCurrentArtifact(null); // Clear artifact when switching threads
    setThreadId(selectedThreadId);
  }, [setThreadId]);

  // Handle new thread creation
  const handleNewThread = useCallback(async () => {
    try {
      // Create a new thread via API
      const response = await fetch("/api/threads", { method: "POST" });
      if (response.ok) {
        const newThread = await response.json();
        console.log("[Thread] Created new thread:", newThread.thread_id);
        setCurrentArtifact(null);
        setThreadId(newThread.thread_id);
        // Refresh thread list to show the new thread
        fetchThreads();
      } else {
        console.error("Failed to create thread:", response.statusText);
      }
    } catch (error) {
      console.error("Failed to create thread:", error);
    }
  }, [setThreadId, fetchThreads]);

  // Callback to update artifact - with deduplication to prevent infinite loops
  // Each unique content key only captures ONCE per page session
  // When user asks to see a document again, agent makes a NEW tool call (different message)
  const captureArtifact = useCallback((artifact: GeneratedArtifact, contentKey: string) => {
    // Skip if already captured this exact content
    if (capturedResultsRef.current.has(contentKey)) {
      return;
    }
    
    // Mark as captured permanently (for this page session)
    capturedResultsRef.current.add(contentKey);
    console.log(`[captureArtifact] Captured: ${contentKey}`);
    setCurrentArtifact(artifact);
  }, []);

  // Listen for the generate_ui tool calls from the agent - uses useRenderToolCall for backend tools
  useRenderToolCall({
    name: "generate_ui",
    description: "Generate rich interactive UI components using Thesys C1",
    parameters: [
      {
        name: "instruction",
        type: "string",
        description: "Natural language description of what UI to generate",
        required: true,
      },
      {
        name: "data",
        type: "object",
        description: "Data to visualize in the UI",
        required: true,
      },
      {
        name: "ui_type",
        type: "string",
        description: "Type of UI: card, timeline, form, chart, table, dashboard, auto",
        required: false,
      },
    ],
    render: ({ args, status, result }) => {
      // Debug logging to understand the result structure
      console.log("[generate_ui] status:", status);
      console.log("[generate_ui] result:", JSON.stringify(result, null, 2));
      console.log("[generate_ui] args:", args);
      
      if (status === "complete" && result?.ui_content) {
        const contentKey = `generate_ui:${result.ui_type}:${(args.instruction as string || '').slice(0, 30)}`;
        console.log("[generate_ui] ✅ Capturing artifact with ui_content");
        captureArtifact({
          ui_content: result.ui_content,
          ui_type: result.ui_type || "auto",
          instruction: args.instruction as string,
          data: args.data as Record<string, unknown>,
        }, contentKey);

        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-emerald-400">✓</span>
              <span className="text-zinc-300">
                Generated {result.ui_type || "UI"} component
              </span>
            </div>
            <p className="text-xs text-zinc-500 mt-1">
              View in main panel →
            </p>
          </div>
        );
      }

      if (status === "inProgress") {
        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700 animate-pulse">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-yellow-400">⏳</span>
              <span className="text-zinc-400">Generating UI component...</span>
            </div>
          </div>
        );
      }

      return <></>;
    },
  });

  // Listen for the generate_artifact tool calls - uses useRenderToolCall for backend tools
  useRenderToolCall({
    name: "generate_artifact",
    description: "Generate long-form documents like reports, presentations, and demand letters",
    parameters: [
      {
        name: "prompt",
        type: "string",
        description: "Natural language description of the document to create",
        required: true,
      },
      {
        name: "artifact_type",
        type: "string",
        description: "Type of artifact: report or slides",
        required: false,
      },
      {
        name: "artifact_id",
        type: "string",
        description: "Optional unique ID for the artifact",
        required: false,
      },
    ],
    render: ({ args, status, result }) => {
      if (status === "complete" && result?.artifact_content) {
        const contentKey = `generate_artifact:${result.artifact_id || ''}:${result.artifact_type || ''}`;
        captureArtifact({
          ui_content: result.artifact_content,
          ui_type: result.artifact_type || "report",
          instruction: args.prompt as string,
          artifact_id: result.artifact_id,
          artifact_type: result.artifact_type,
        }, contentKey);

        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-emerald-400">📄</span>
              <span className="text-zinc-300">
                Generated {result.artifact_type || "document"}
              </span>
            </div>
            <p className="text-xs text-zinc-500 mt-1">
              ID: {result.artifact_id} • View in main panel →
            </p>
          </div>
        );
      }

      if (status === "inProgress") {
        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700 animate-pulse">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-yellow-400">📝</span>
              <span className="text-zinc-400">Generating document...</span>
            </div>
          </div>
        );
      }

      return <></>;
    },
  });

  // Listen for the show_medical_overview tool calls (custom template with GCS signed URLs) - uses useRenderToolCall for backend tools
  useRenderToolCall({
    name: "show_medical_overview",
    description: "Display medical treatment overview with clickable document links",
    parameters: [
      {
        name: "project_name",
        type: "string",
        description: "The case folder name (e.g., 'Abby-Sitgraves-MVA-7-13-2024')",
        required: true,
      },
      {
        name: "url_expiration_minutes",
        type: "number",
        description: "How long signed URLs remain valid (default: 60)",
        required: false,
      },
    ],
    render: ({ args, status, result }) => {
      console.log("[show_medical_overview] status:", status);
      console.log("[show_medical_overview] result:", JSON.stringify(result, null, 2));

      if (status === "complete" && result?.success && result?.data) {
        const contentKey = `show_medical_overview:${args.project_name}`;
        console.log("[show_medical_overview] ✅ Capturing medical overview artifact");
        captureArtifact({
          ui_content: "", // Not using C1 for this
          ui_type: "medical_overview",
          instruction: `Medical overview for ${args.project_name}`,
          component: "MedicalTreatmentOverview",
          componentData: result.data,
        }, contentKey);

        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-purple-400">🏥</span>
              <span className="text-zinc-300">
                Medical Treatment Overview loaded
              </span>
            </div>
            <p className="text-xs text-zinc-500 mt-1">
              {result.data.providers?.length || 0} providers • {result.data.total_billed ? `$${result.data.total_billed.toLocaleString()} billed` : ''} • View in main panel →
            </p>
          </div>
        );
      }

      if (status === "complete" && result?.error) {
        return (
          <div className="p-3 bg-red-900/30 rounded-lg border border-red-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-red-400">❌</span>
              <span className="text-red-300">Failed to load medical overview</span>
            </div>
            <p className="text-xs text-red-400 mt-1">{result.error}</p>
          </div>
        );
      }

      if (status === "inProgress") {
        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700 animate-pulse">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-purple-400">🏥</span>
              <span className="text-zinc-400">Loading medical overview...</span>
            </div>
          </div>
        );
      }

      return <></>;
    },
  });

  // Universal UI script execution action - uses useRenderToolCall for backend tools
  useRenderToolCall({
    name: "render_ui_script",
    description: "Execute a UI script (Python) and return component data for frontend rendering",
    parameters: [
      {
        name: "script_path",
        type: "string",
        description: "Path to the UI script relative to Tools/ (e.g., 'UI/case_dashboard.py' or 'UI/_generated/custom.py')",
        required: true,
      },
      {
        name: "script_args",
        type: "object",
        description: "Optional list of command-line arguments for the script",
        required: false,
      },
    ],
    render: ({ args, status, result }) => {
      console.log("[render_ui_script] status:", status);
      console.log("[render_ui_script] result:", JSON.stringify(result, null, 2));

      if (status === "complete" && result?.success && result?.component && result?.data) {
        // Use file_path from data for documents, or component name as fallback
        const docPath = result.data?.file_path || result.data?.path || '';
        const contentKey = `render_ui_script:${result.component}:${docPath}`;
        console.log(`[render_ui_script] ✅ Capturing artifact for component: ${result.component}, key: ${contentKey}`);
        captureArtifact({
          ui_content: "",
          ui_type: "ui_script",
          instruction: `UI script: ${args.script_path}`,
          component: result.component,
          componentData: result.data,
        }, contentKey);

        // Get badge info for the component type
        const getBadgeInfo = (component: string) => {
          switch (component) {
            case "CaseDashboard":
              return { icon: "📊", label: "Case Dashboard" };
            case "CaseSnapshot":
              return { icon: "📋", label: "Case Snapshot" };
            case "MedicalTreatmentOverview":
              return { icon: "🏥", label: "Medical Overview" };
            case "MedicalProviderCard":
              return { icon: "👨‍⚕️", label: "Provider Details" };
            case "InsuranceCoverageCard":
            case "InsuranceOverview":
              return { icon: "🛡️", label: "Insurance" };
            case "LienCard":
              return { icon: "📑", label: "Lien Details" };
            case "ExpenseCard":
              return { icon: "💰", label: "Expense Details" };
            case "ContactCard":
              return { icon: "👤", label: "Contact Card" };
            case "NegotiationsView":
              return { icon: "🤝", label: "Negotiations" };
            case "ComposedView":
              return { icon: "✨", label: "Custom View" };
            case "NotesView":
              return { icon: "📝", label: "Case Notes" };
            case "CalendarView":
              return { icon: "📅", label: "Calendar" };
            case "DocumentViewer":
              return { icon: "📄", label: "Document Viewer" };
            default:
              return { icon: "📄", label: component };
          }
        };

        const badge = getBadgeInfo(result.component);

        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-emerald-400">{badge.icon}</span>
              <span className="text-zinc-300">{badge.label} loaded</span>
            </div>
            <p className="text-xs text-zinc-500 mt-1">
              Script: {args.script_path} • View in main panel →
            </p>
          </div>
        );
      }

      if (status === "complete" && result?.error) {
        return (
          <div className="p-3 bg-red-900/30 rounded-lg border border-red-700">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-red-400">❌</span>
              <span className="text-red-300">Failed to render UI</span>
            </div>
            <p className="text-xs text-red-400 mt-1">{result.error}</p>
            {result.raw_output && (
              <details className="mt-2">
                <summary className="text-xs text-zinc-500 cursor-pointer">Show raw output</summary>
                <pre className="text-xs text-zinc-600 mt-1 overflow-auto max-h-32">{result.raw_output}</pre>
              </details>
            )}
          </div>
        );
      }

      if (status === "inProgress") {
        return (
          <div className="p-3 bg-zinc-800/50 rounded-lg border border-zinc-700 animate-pulse">
            <div className="flex items-center gap-2 text-sm">
              <span className="text-yellow-400">⏳</span>
              <span className="text-zinc-400">Running UI script: {args.script_path}...</span>
            </div>
          </div>
        );
      }

      return <></>;
    },
  });

  // NOTE: Streaming hooks (useCoAgentStateRender, useCopilotAction with "*") were removed
  // They were causing "Message not found" errors and breaking chat rendering.
  // TODO: Re-implement streaming UI feedback once the root cause is understood.

  return (
    <div className="h-screen flex bg-zinc-950">
      {/* Thread list sidebar (left) */}
      {showThreadList && (
        <ThreadList
          threads={threads}
          currentThreadId={currentThreadId || null}
          onSelectThread={handleSelectThread}
          onNewThread={handleNewThread}
          isLoading={isLoadingThreads}
        />
      )}

      {/* Toggle thread list button */}
      <button
        onClick={() => setShowThreadList(!showThreadList)}
        className="absolute top-4 left-4 z-50 p-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 transition-colors text-zinc-400"
        style={{ left: showThreadList ? "16.5rem" : "1rem" }}
      >
        {showThreadList ? "◀" : "▶"}
      </button>

      {/* Main content area for artifacts */}
      <MainContent artifact={currentArtifact} />

      {/* Chat sidebar (right) */}
      <CopilotSidebar
        defaultOpen
        instructions={`You are Roscoe, an AI paralegal assistant. You help with:
- Legal research and case analysis
- Drafting demand letters and legal documents  
- Managing case files and deadlines
- Creating visual summaries and exhibits
- Analyzing evidence including images, videos, and documents

**IMPORTANT: When displaying case information, use the appropriate UI tool:**

**For Medical Treatment Overview** (providers, files, billing):
- Use show_medical_overview tool with just the project_name
- This displays providers with clickable document links
- Example: "Show medical overview for Abby Sitgraves" → show_medical_overview("Abby-Sitgraves-MVA-7-13-2024")

**For other rich UI** (case cards, timelines, dashboards):
- Use generate_ui tool with appropriate ui_type
- Examples:
  - "Show me the case card for [client]" → generate_ui with ui_type="card"
  - "Create a timeline of treatments" → generate_ui with ui_type="timeline"  
  - "Calculate the damages" → generate_ui with ui_type="dashboard"

Be professional, thorough, and always cite sources when discussing legal matters.`}
        labels={{
          title: "Roscoe",
          initial: "Hi! I'm Roscoe, your AI paralegal. Ask me to show medical overviews, case cards, or any case information!",
        }}
      />
    </div>
  );
}
