#!/bin/bash
# Case File Reorganization Script
# Generated by Roscoe for: {CASE_NAME}
# Date: {DATE}

# Navigate to case directory
cd "/path/to/case/directory"

# Create 5-bucket directory structure if it doesn't exist
mkdir -p "Client"
mkdir -p "Investigation"
mkdir -p "Medical Records"
mkdir -p "Insurance"
mkdir -p "Litigation"

# ============================================
# CLIENT FILES
# ============================================
# Documents between Firm and Client
mv "old-filename.pdf" "Client/YYYY-MM-DD - Client Name - Client - Originator - Description.pdf"

# ============================================
# INVESTIGATION FILES
# ============================================
# Hard evidence, photos, police reports, incident documentation
mv "old-filename.pdf" "Investigation/YYYY-MM-DD - Client Name - Investigation - Originator - Description.pdf"

# ============================================
# MEDICAL RECORDS FILES
# ============================================
# Clinical notes, bills, provider documents, HIPAA authorizations
mv "old-filename.pdf" "Medical Records/YYYY-MM-DD - Client Name - Medical Record - Originator - Description.pdf"

# Batch rename for multiple similar files (example: NEF emails)
# for f in pattern*.ext; do
#     mv "$f" "Litigation/${f%.ext} - renamed.ext"
# done

# ============================================
# INSURANCE FILES
# ============================================
# Carrier correspondence, demands, lien notices
mv "old-filename.pdf" "Insurance/YYYY-MM-DD - Client Name - Insurance - Originator - Description.pdf"

# ============================================
# LITIGATION FILES
# ============================================
# Court filings, pleadings, discovery, motions
mv "old-filename.pdf" "Litigation/YYYY-MM-DD - Client Name - Litigation - Originator - Description.pdf"

# ============================================
# DELETE DUPLICATES
# ============================================
# Remove duplicate files (only after user approval)
# rm "duplicate-file.pdf"

echo "File reorganization complete!"
echo "Total files moved: [COUNT]"
echo "Files by bucket:"
echo "  Client: [COUNT]"
echo "  Investigation: [COUNT]"
echo "  Medical Records: [COUNT]"
echo "  Insurance: [COUNT]"
echo "  Litigation: [COUNT]"
echo "Duplicates deleted: [COUNT]"
