"use client";

import { useState, useCallback, useEffect } from "react";
import { artifactRegistry } from "./registry";
import { ArtifactProps } from "./types";

interface ArtifactInstance {
  id: string;
  componentId: string;
  data: Record<string, any>;
}

interface ArtifactCanvasProps {
  /** Initial artifacts to render */
  initialArtifacts?: ArtifactInstance[];
  /** Callback when artifact actions occur */
  onArtifactAction?: (artifactId: string, action: string, payload: any) => void;
}

/**
 * Canvas for rendering dynamic artifacts generated by the agent
 * Follows Claude Artifacts pattern - agent generates UI, canvas renders it
 */
export function ArtifactCanvas({ initialArtifacts = [], onArtifactAction }: ArtifactCanvasProps) {
  const [artifacts, setArtifacts] = useState<ArtifactInstance[]>(initialArtifacts);

  const handleArtifactAction = useCallback(
    (artifactId: string, action: string, payload: any) => {
      console.log(`Artifact ${artifactId} action:`, action, payload);
      onArtifactAction?.(artifactId, action, payload);
    },
    [onArtifactAction]
  );

  const addArtifact = useCallback((componentId: string, data: Record<string, any>) => {
    const id = `artifact-${Date.now()}-${Math.random().toString(36).slice(2)}`;
    setArtifacts((prev) => [...prev, { id, componentId, data }]);
    return id;
  }, []);

  const removeArtifact = useCallback((id: string) => {
    setArtifacts((prev) => prev.filter((a) => a.id !== id));
  }, []);

  const updateArtifact = useCallback((id: string, data: Record<string, any>) => {
    setArtifacts((prev) =>
      prev.map((a) => (a.id === id ? { ...a, data } : a))
    );
  }, []);

  // Expose methods for CopilotKit tools via window.__artifactCanvas
  useEffect(() => {
    if (typeof window !== "undefined") {
      (window as any).__artifactCanvas = {
        add: addArtifact,
        remove: removeArtifact,
        update: updateArtifact,
      };
    }

    // Cleanup on unmount
    return () => {
      if (typeof window !== "undefined") {
        delete (window as any).__artifactCanvas;
      }
    };
  }, [addArtifact, removeArtifact, updateArtifact]);

  return (
    <div className="artifact-canvas space-y-4 p-4">
      {artifacts.length === 0 && (
        <div className="text-center text-muted-foreground py-12">
          <p>No artifacts yet</p>
          <p className="text-sm mt-2">Ask Roscoe to create something!</p>
        </div>
      )}

      {artifacts.map((artifact) => {
        const componentDef = artifactRegistry.get(artifact.componentId);
        if (!componentDef) {
          console.error(`Component ${artifact.componentId} not found in registry`);
          return (
            <div key={artifact.id} className="text-red-500 p-4 border border-red-300 rounded">
              Unknown component: {artifact.componentId}
            </div>
          );
        }

        const Component = componentDef.component;
        return (
          <div key={artifact.id} className="artifact-instance">
            <Component
              artifactId={artifact.id}
              data={artifact.data}
              onAction={(action: string, payload: any) => handleArtifactAction(artifact.id, action, payload)}
            />
          </div>
        );
      })}
    </div>
  );
}
